### ISSUE TITLE
scan aps MicroSD Problems

### ISSUE THREAD

**Issue by LuckyFishGeek** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#67]
device : ![image](https://github.com/user-attachments/assets/227c5570-fcf1-4919-8275-50969aa6b472)

Encountered problems:When using the scan aps function, instead of calling the SD card space, it uses the space built into the ESP32, causing the capacity to be filled and the device to restart.I have tested many SD cards, so it should not be an issue with the SD card! The SD card has been formatted into FAT and FAT32 formats, but the same problem still occurs after testing.

![41ca25eb6534b6f266320ffb9d60fde8_720](https://github.com/user-attachments/assets/bec62b7c-2407-4d0c-8766-5b9b076f9d78)

The storage capacity resources are continuously decreasing.
![image](https://github.com/user-attachments/assets/83815d12-aec6-49a8-b644-dc1f814ecca9)

![image](https://github.com/user-attachments/assets/b9430472-44ea-4174-997f-3c7a65fc42a4)

When the storage resources are exhausted, the device will restart. Could the issue be with the code in the scan aps function that writes to the memory card?

![image](https://github.com/user-attachments/assets/2f111f6c-2965-47fb-83d6-09af25d3f4a1)

I can see the files generated by the scan aps function in the SD card, which indicates that it can normally generate and write data on the SD card. So this is a very strange problem.

**Comment by Lgndwilloske** [comment]
alot of people have been having issues with sd cards, i think it might be down to the model of esp you have. Wait for fr4nk to give a response

**Comment by ICodKid** [comment]
ESP32Marauder Cheap-Yellow-Display Initialising SD Fail Fix That Worked for Me

I was having a problem with my micro SD card failing to initialise. I tried resetting and reformatting it, but that didn’t work. The solution that finally worked was deleting all partitions on the SD card and creating a smaller partition of 4GB. My SD card was originally 15GB. After reformatting it to FAT32 and plugging it in, it worked, and I could start uploading the Evil Portal. It took me three days to figure this out since there aren’t a lot of good answers online. I’m not sure if this is a permanent solution, but it worked for me.
